accounts/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'login/', 'accounts.views.login', name = 'login'),
    url(r'register/', 'accounts.views.register', name = 'register'),
    url(r'forgot_password/', 'accounts.views.forgot_password', name = 'forgot_password'),
]

pietrack/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^accounts', include('accounts.urls', namespace='accounts')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
	url(r'^create-project/$',views.create_project,name='create_project'),
	url(r'^list-of-projects/$', views.list_of_projects, name='list_of_projects'),
	url(r'^project-description/(?P<pk>[0-9]+)/$', views.project_description, name='project_description'),
]

templates/base.html
{% load compress %}
<!DOCTYPE html>
<html>
  <head>
    <title>pieT</title>
    {% load staticfiles %}
    <link href='http://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700italic,700,900,900italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,500,300,600,700,800,900' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    {% compress css %}
    <link rel="stylesheet" type="text/less" href="{% static 'less/slim_scroll.less' %}">
    <link rel="stylesheet" type="text/less" href="{% static 'less/main.less' %}">
    {% endcompress %}
  </head>
  <body>
    <header id='header_base'>
      <!-- logo -->
      <span class="logo">
      <i class='fa fa-pie-chart'></i>
      </span>
      <!--/ logo -->
      <!-- project mgmt -->
      <span class='pg_mt'>
      <i class='fa fa-bookmark-o'></i>
      </span>
      <!--/ project mgmt -->
      <!-- left menu -->
      <div class='left_header'>
        <div class="menu">
          <ul>
            {%block headerline%}
            {%endblock headerline%}
          </ul>
        </div>
      </div>
      <!--/ left menu -->
      <!-- right header -->
      <div class='right_header'>
        <div class="menu">
          <ul>
            <li class='parent_list'>
              <span class='each_wrap extras'>
              <i class='fa fa-arrow-down'></i>
              <span class='name'>Extras</span>
              </span>
              <ul class="sub_list_extras">
                <li>
                  <span class='extras_drop_child extras_one'>
                  <i class='fa fa-user'></i>
                  <span class='name'>Profile</span>
                  </span>
                  </span>
                </li>
                <li>
                  <span class='extras_drop_child extras_two'>
                  <i class='fa fa-expeditedssl'></i>
                  <span class='name'>Change Password</span>
                  </span>
                  </span>
                </li>
              </ul>
            </li>
            <li class='parent_list'>
              <span class='each_wrap notification'>
              <i class='fa fa-bell'></i>
              <span class='name'>Notifications</span>
              <span class='number count'>25</span>
              </span>
              <div class='scroll'>
                <ul class='sub_list'>
                  <li>
                    <span class='ticket'>
                    <img src='http://i.stack.imgur.com/8sNfT.jpg'>
                    <span class='description'>
                    <span class='name'>Nazneen</span>
                    added you to project
                    <span class='project'>Pie Track</span>
                    <span class='time'>12 min ago</span>
                    </span>
                    </span>
                  </li>
                  <li>
                    <span class='ticket'>
                    <img src='http://i.stack.imgur.com/8sNfT.jpg'>
                    <span class='description'>
                    <span class='name'>Nazneen</span>
                    added you to project
                    <span class='project'>Pie Track</span>
                    <span class='time'>12 min ago</span>
                    </span>
                    </span>
                  </li>
                  <li>
                    <span class='ticket'>
                    <img src='http://i.stack.imgur.com/8sNfT.jpg'>
                    <span class='description'>
                    <span class='name'>Nazneen</span>
                    added you to project
                    <span class='project'>Pie Track</span>
                    <span class='time'>12 min ago</span>
                    </span>
                    </span>
                  </li>
                  <li>
                    <span class='ticket'>
                    <img src='http://i.stack.imgur.com/8sNfT.jpg'>
                    <span class='description'>
                    <span class='name'>Nazneen</span>
                    added you to project
                    <span class='project'>Pie Track</span>
                    <span class='time'>12 min ago</span>
                    </span>
                    </span>
                  </li>
                  <li>
                    <span class='ticket'>
                    <img src='http://i.stack.imgur.com/8sNfT.jpg'>
                    <span class='description'>
                    <span class='name'>Nazneen</span>
                    added you to project
                    <span class='project'>Pie Track</span>
                    <span class='time'>12 min ago</span>
                    </span>
                    </span>
                  </li>
                  <li>
                    <span class='ticket'>
                    <img src='http://i.stack.imgur.com/8sNfT.jpg'>
                    <span class='description'>
                    <span class='name'>Nazneen</span>
                    added you to project
                    <span class='project'>Pie Track</span>
                    <span class='time'>12 min ago</span>
                    </span>
                    </span>
                  </li>
                  <li>
                    <span class='ticket'>
                    <img src='http://i.stack.imgur.com/8sNfT.jpg'>
                    <span class='description'>
                    <span class='name'>Nazneen</span>
                    added you to project
                    <span class='project'>Pie Track</span>
                    <span class='time'>12 min ago</span>
                    </span>
                    </span>
                  </li>
                  <li>
                    <span class='ticket'>
                    <img src='http://i.stack.imgur.com/8sNfT.jpg'>
                    <span class='description'>
                    <span class='name'>Nazneen</span>
                    added you to project
                    <span class='project'>Pie Track</span>
                    <span class='time'>12 min ago</span>
                    </span>
                    </span>
                  </li>
                  <li>
                    <span class='ticket'>
                    <img src='http://i.stack.imgur.com/8sNfT.jpg'>
                    <span class='description'>
                    <span class='name'>Nazneen</span>
                    added you to project
                    <span class='project'>Pie Track</span>
                    <span class='time'>12 min ago</span>
                    </span>
                    </span>
                  </li>
                  <li>
                    <span class='ticket'>
                    <img src='http://i.stack.imgur.com/8sNfT.jpg'>
                    <span class='description'>
                    <span class='name'>Nazneen</span>
                    added you to project
                    <span class='project'>Pie Track</span>
                    <span class='time'>12 min ago</span>
                    </span>
                    </span>
                  </li>
                  <li>
                    <span class='ticket'>
                    <img src='http://i.stack.imgur.com/8sNfT.jpg'>
                    <span class='description'>
                    <span class='name'>Nazneen</span>
                    added you to project
                    <span class='project'>Pie Track</span>
                    <span class='time'>12 min ago</span>
                    </span>
                    </span>
                  </li>
                </ul>
              </div>
            </li>
            <li>
              <span class='each_wrap logout'>
              <i class='fa fa-power-off'></i>
              <span class='name'>Logout</span>
              </span>
            </li>
          </ul>
        </div>
        <span class="name_img_wrap">
        <span class='name'>
        Hello, <span>Nazneen Shaik</span>
        </span>
        <img src='http://epicwpp.com/wp-content/uploads/Smiling-minions-Frank-and-Dave-holding-a-Seastar_www.EpicWpp.com_.jpg'>
      </div>
      </div>
      <!--/ right header -->
    </header>
    {%block content%}
	{%endblock content%}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'js/jquery.slimscroll.js' %}"></script>
    <script type="text/javascript">
      $(function(){
        $('.scroll').slimscroll({
          alwaysVisible: false,
          height: 400
        });
      });
      $('.sub_list,.sub_list_extras').mouseenter(function(event) {
      	$(this).closest('.parent_list').addClass('active_li_drop')
      });
      $('.sub_list,.sub_list_extras').mouseleave(function(event) {
      	$(this).closest('.parent_list').removeClass('active_li_drop')
      });

      {%block create_project_js%}
      {%endblock create_project_js%}

    </script>
  </body>
</html>

templates/create_project.html
{%extends 'base.html'%}
{%block content%}
{%load staticfiles%}
    <section id='base_content' class='create_project'>
      <div class="content_box">
        <div class="title">
          <h4>Create your project to access</h4>
          <div class="tag">Compellingly reintermediate premier materials for client-centered markets.for client-centered markets.</div>
        </div>
        <!-- create project form start-->
        <form action="" method="post" id="id_form_cproject">
          {%csrf_token%}
          <div class="panel_box">
            <div class="form_group">
              <label>Project title</label>
              <input name='name' type="text" class='input'>
              <span name="pname_error"></span><!--Error here -->
              <div class="help">Dynamically maximize professional models whereas.</div>
            </div>
            <div class="form_group">
              <label>Description</label>
              <textarea name='description' class='textarea'></textarea>
              <span name="pdescription_error"></span><!--Error here -->
              <div class="help">Dynamically maximize professional models whereas.</div>
            </div>
            <button id="id_submit_cproject">create project</button>
          </div>
        </form>
        <!-- create project form end -->
  {%endblock content%}

      {%block create_project_js%}
      /*Backend code start */
        function send_error(error)
          {
              if(error)
                  return error;
              return "";
          }
        $('#id_form_cproject').on('submit',function(e){
          $.post('',$('#id_form_cproject').serialize(),function(response){
            if(response['error']){
              $("span[name='pname_error']").text(send_error(response['errors'].name));
              $("span[name='pdescription_error']").text(send_error(response['errors'].description));
            }
            else{
              /*redirect page here */
              alert("Redirect this page (project created)");
            }
          });
          e.preventDefault();
        });
      /*Backed code end*/
      {%endblock create_project_js%}

templates/list_of_projects.html
{%extends 'base.html'%}
{%block content%}
<section id='base_content'>
  <div class="list_of_projects">
    <div class="title">
      <div class="center">
        <span>Enthusiastically empower front-end web-readiness vis-a-vis frictionless schemas. Globally architect.</span>
        <div class="left">my projects</div>
        <div class="right"><a href="{% url 'project:create_project' %}"><button>create Project</button></div></a>
      </div>
    </div>
    <div class="table_div">
      <table class='table table-hover'>
        <tbody>
          {% for project in projects_list %}
          <tr data-href="{% url 'project:project_description' project.id %}">
            <td><img src='http://www.freelargeimages.com/wp-content/uploads/2014/12/Happy_birthday_minions-4.jpg'></td>
            <td>
              <h2>{{project.name}}</h2>
              <p>{{project.description}}</p>
            </td>
            <td width="15%">
              <p>{{project.created_date}}</p>
              <p>{{request.user.username}}</p>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>
{%endblock content%}

{%block create_project_js%}

$('tr[data-href]').on("click", function() {
    document.location = $(this).data('href');
});

{%endblock create_project_js%}

templates/login.html
{% load compress %}
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <title>pieT</title>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700italic,700,900,900italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,500,300,600,700,800,900' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    {% compress css %}
    <link rel="stylesheet" type="text/less" href="{% static 'less/hexagon.less' %}">
    <link rel="stylesheet" type="text/less" href="{% static 'less/main.less' %}">
    {% endcompress %}
  </head>
  <body class="container login_container">
    <!--header -->
    <header>
      <div class='logo'>
        <span>PIE TRACK</span>
      </div>
      <div class='text'>
        <h3>Track your project</h3>
        <div class="tag">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed malesuada justo. Nam sed lectus vel sem accumsan mollis.</div>
      </div>
      <div class="clearfix"></div>
    </header>
    <!--/ headetr -->
    <!-- content -->
    <div class="row login_content">
      <!-- form div -->
      <div class="form_div">
        <span class='icon-hexagon1 hex1_left'></span>
        <span class='icon-hexagon1 hex2_left'></span>
        <span class='icon-hexagon1 hex3_left'></span>
        <span class='icon-hexagon1 hex1_right'></span>
        <span class='icon-hexagon1 hex2_right'></span>
        <span class='icon-hexagon1 hex3_right'></span>
        <span class='icon-hexagon1 hex4_right'></span>
        <!-- tag -->
        <div class="border_div login">
          <div class="content_wrap">
            <div class="icon_div">
              <span class='icon-hexagon1 hex1_dash_left'></span>
              <i class='fa fa-users icon_upon'></i>
            </div>
            <div class="button_div">
              <button class='login_panel_tab_button' panelId='login'>login</button>
            </div>
          </div>
        </div>
        <!--/ tag -->
        <!-- tag -->
        <div class="border_div forgot_pass">
          <div class="content_wrap">
            <div class="icon_div">
              <span class='icon-hexagon1 hex1_dash_left'></span>
              <i class='fa fa-users icon_upon'></i>
            </div>
            <div class="button_div">
              <button class='login_panel_tab_button' panelId='forgot_password'>Forgot Password</button>
            </div>
          </div>
        </div>
        <!--/ tag -->
        <!-- tag -->
        <div class="border_div create_acc">
          <div class="content_wrap">
            <div class="icon_div">
              <span class='icon-hexagon1 hex1_dash_left'></span>
              <i class='fa fa-users icon_upon'></i>
            </div>
            <div class="button_div">
              <button class='login_panel_tab_button' panelId='create_account'>Create Account</button>
            </div>
          </div>
        </div>
        <!--/ tag -->
        <!-- tag -->
        <div class="border_div pm">
          <div class="content_wrap">
            <div class="icon_div">
              <span class='icon-hexagon1 hex1_dash_left'></span>
              <i class='fa fa-users icon_upon'></i>
            </div>
            <div class="ticket">
              <h3>Project Management</h3>
              <div class="tag_description"> Quisque vehicula euismod lacinia. Ut diam sem, rutrum ut lectus et, tempor </div>
            </div>
          </div>
        </div>
        <!--/ tag -->
        <!-- tag -->
        <div class="border_div tm">
          <div class="content_wrap">
            <div class="icon_div">
              <span class='icon-hexagon1 hex1_dash_left'></span>
              <i class='fa fa-users icon_upon'></i>
            </div>
            <div class="ticket">
              <h3>Time Management</h3>
              <div class="tag_description"> Quisque vehicula euismod lacinia. Ut diam sem, rutrum ut lectus et, tempor </div>
            </div>
          </div>
        </div>
        <!--/ tag -->
        <!-- tag -->
        <div class="border_div milestones">
          <div class="content_wrap">
            <div class="icon_div">
              <span class='icon-hexagon1 hex1_dash_left'></span>
              <i class='fa fa-users icon_upon'></i>
            </div>
            <div class="ticket">
              <h3>Create Milestones</h3>
              <div class="tag_description"> Quisque vehicula euismod lacinia. Ut diam sem, rutrum ut lectus et, tempor </div>
            </div>
          </div>
        </div>
        <!--/ tag -->
        <!-- tag -->
        <div class="border_div teams">
          <div class="content_wrap">
            <div class="icon_div">
              <span class='icon-hexagon1 hex1_dash_left'></span>
              <i class='fa fa-users icon_upon'></i>
            </div>
            <div class="ticket">
              <h3>Assign teams</h3>
              <div class="tag_description"> Quisque vehicula euismod lacinia. Ut diam sem, rutrum ut lectus et, tempor </div>
            </div>
          </div>
        </div>
        <!--/ tag -->
        <!-- create_div -->
            <div class="create_div" id='create_account'>
        <form id = 'form_create_account_id' method = 'POST' action = "{% url 'accounts:register' %}">
            <div class="title_flap">Create account</div>
            <div class="form-group">
              <label>Email address</label>
              <input id = 'email_id' name = 'email' type="email" class="form-control"><span id = 'error_email_id'></span>
            </div>
            <div class="form-group">
              <label>Full name</label>
              <input id = 'first_name_id' name = 'first_name' type="text" class="form-control"><span id = 'error_first_name_id'></span>
            </div>
            <div class="form-group">
              <label>Password</label>
              <input id = 'password_id' name = 'password' type="password" class="form-control"><span id = 'error_password_id'></span>
            </div>
            <div class="form-group">
              <label>Confirm passowrd</label>
              <input id = 'confirm_password_id' name = 'confirm_password' type="password" class="form-control"><span id = 'error_confirm_password_id'></span>
            </div>
            <div class="form-group">
              <label>user name (case sensitive)</label>
              <input id = 'username_id' name = 'username' type="text" class="form-control"><span id = 'error_username_id'></span>
            </div>
            <div class="form-group">
              <label>organization</label>
              <input id = 'organization_id' name = 'organization' type="text" class="form-control"><span id = 'error_organization_id'></span>
            </div>
            <div class="form-group">
                <button id = 'create_account_button_id' type = 'submit' class='button'>Sign up for free</button>
            </div>
            <!--<div class="form-group">
              <span class='tag_text'>Are you an exixting member? <a>log in</a></span>
            </div>-->
            {% csrf_token %}
        </form>
            </div>

        <!-- create div -->
        <!-- forget login -->
        <div class="forgot_login_div active">
        <div class="bg_blur"></div>
        <!--login -->
            <div class="login_active actvive_login_forgot" id='login'>
        <form id = 'form_login_id' method = 'POST'>
              <div class="title_flap">login</div>
            <div class="form-group">
              <label>Email address</label>
              <input id = 'login_email_id' name = 'email' type="email" class="form-control">
            </div>
            <div class="form-group">
              <label>Password</label>
              <input id = 'login_password_id' name = 'password' type="password" class="form-control"><span id = 'login_error_id'></span>
            </div>
            <div class="form-group">
              <button id = 'login_button_id' class='button'>LOgin</button>
            </div>
            {% csrf_token %}
        </form>
            </div>
        <!--/ login -->
        <!-- forgot password -->
            <div class="forgot_active" id='forgot_password'>
        <form id = 'form_forgot_password_id' method = 'POST'>
              <div class="title_flap forgot_flap">forgot password</div>
            <div class="form-group">
              <label>Email address</label>
              <input id = 'fp_email_id' name = 'email' type="email" class="form-control" ><span id = 'error_fp_email_id'></span>
            </div>
            <div class="form-group">
                <button id = 'forgot_password_button_id' class='button'>Reset password</button>
            </div>
        <!--/ forgot password -->
        </div>
        <!--/ forget login -->
      </div>
      <!--/ form div -->
            {% csrf_token %}
        </form>
    </div>
    <!--/ content -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'js/hexagon.js' %}"></script>
    <script type="text/javascript">
    $('.login_panel_tab_button').click(function(e){
      var id=$(this).attr('panelId');
      var btn_bg=$(this).css('border-color');
      $('.form_div').children('div').removeClass('active');
      $('.login_panel_tab_button').removeClass('active_button').css('color','inherit');
      
      $(this).addClass('active_button').css('color',btn_bg);
      if(id== 'create_account'){
        $('#'+id).addClass('active');
      }
      else{
        $('.forgot_login_div').addClass('active').children().removeClass('actvive_login_forgot');
        $('#'+id).addClass('actvive_login_forgot');
      }
    })
    </script>
    
    <!--login script-->
    <script>
        $('#login_button_id').click(function(event){
                event.preventDefault();
                $.post("", $('#form_login_id').serialize(), function(result){
                    if(result.error === true){
                        $('#login_error_id').text(result.error_msg)
                    }
                    else{
                        alert('logged_in') 
                    }
                });
        });
    </script>

    <script>
        function disp_error(result){
            if(result){
                return result;
            }
            else{
                return '';
            }
        }
    </script>

    <script>
        $('#create_account_button_id').click(function(event){
                event.preventDefault();
                $.post("{% url 'accounts:register' %}", $('#form_create_account_id').serialize(), function(result){
                    if(result['form_errors']){
                        $('#error_email_id').text(disp_error(result['form_errors'].email))
                        $('#error_username_id').text(disp_error(result['form_errors'].username))
                        $('#error_password_id').text(disp_error(result['form_errors'].password))
                        $('#error_confirm_password_id').text(disp_error(result['form_errors'].confirm_password))
                        $('#error_organization_id').text(disp_error(result['form_errors'].organization))
                    }
                    else if(result['error_password']){
                            $('#error_confirm_password_id').text(result['error_password'])
                    }
                    else{
                        alert('user_created')
                    }
                });
        });
    </script>
    
    <script>
        $('#forgot_password_button_id').click(function(event){
                event.preventDefault();
                $.post("{% url 'accounts:forgot_password' %}", $('#form_forgot_password_id').serialize(), function(result){
                    if(result['error']){
                        $('#error_fp_email_id').text(disp_error(result['error_msg']))
                    }
                    else{
                        alert('forgot password done')
                    }
                });
        });
    </script>
  </body>
</html>